### ISSUE TITLE
Minor issues with scala memory generation

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#12]
There are a couple of issues:

1) scram_p2a0.WREN := blackbox.io.scram_p2a_wren as a first of the scram_p2a0 node connections is actually commented out in Scala as it is generated in the same line as the previous comment:

// -> {"WREN":1,"RDEN":1,"BEN":1,"WRADDR":"addrWidth","WRDATA":"dataWidth","RDADDR":"addrWidth","RDDATA":"-dataWidth"}scram_p2a0.WREN := blackbox.io.scram_p2a_wren

2) There is a tie to 1 generated for the BEN signal, but the signal is optional and in our case it is not a part of the interface, and it is not generated in the scram_p2a bundle, so the error is reported for the following connection:

    scram_p2a0.BEN := true.B // BEN

No BEN in the Bundle:
class scram_p2aBundle() extends Bundle {
  val `WRADDR` = Output(UInt((11).W))
  val `WREN` = Output(Bool())
  val `RDADDR` = Output(UInt((11).W))
  val `WRDATA` = Output(UInt((256).W))
  val `RDDATA` = Input(UInt((256).W))
  val `RDEN` = Output(Bool())
  val `RDERR` = Input(UInt((4).W))
}
3) Generated scala has a long type parameter in SyncReadMem, the compiler reports overloaded apply method in that case, and it works if L is removed from the following line:
val scram_p2aMem = SyncReadMem(2048L, Vec(1, UInt((256).W)))

**Comment by albertchen-sifive** [comment]
this should be fixed by https://github.com/sifive/duh-scala/pull/22 and https://github.com/sifive/duh-scala/pull/27
