### ISSUE TITLE
Upper case characters error when compiling Scala

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#14]
The generated code is:
    val (PMA0CPUDMEM0, _) = PMA0CPUDMEMNode.out(0)
and it reports an error.

The error is removed when the code is changed to:
    val (pma0cpudmem0, _) = PMA0CPUDMEMNode.out(0)

**Comment by drom** [comment]
@jackkoenig do I understand correctly, that first capital letter in the identifier in Scala is special for ... Classes?
