### ISSUE TITLE
Memories clocking

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#35]
Currently no matter which clock we map to the memory interface, the generated Scala looks the same. How is this clock source information processed by duh tool?

**Comment by albertchen-sifive** [comment]
It depends on where you are looking. The memory instantiation and connections may look the same even if the port maps change. The important bits are the connections in the `L*Base` module. For example this duh document
```javascript
{
  component: {
    vendor: 'sifive',
    library: 'blocks',
    name: 'example',
    version: '0.1.0',
    model: {
      views: [{
        name: 'RTLview',
        displayName: 'RTL View',
        description: 'Simple RTL view of a component.',
        envIdentifier: '*Synthesis:',
        componentInstantiationRef: 'VerilogModel'
      }],
      instantiations: [],
      ports: {
        MEM_CLK1: -1,
        MEM_CLK2: -1,
        MEM_WREN: -1,
        MEM_RDEN: -1,
        MEM_BEN: -4,
        MEM_ADDR: -8,
        MEM_WRDATA: -32,
        MEM_RDDATA: 32
      }
    },
    busInterfaces: [{
      name: 'PIOMEM',
      interfaceMode: 'master',
      busType: {vendor: 'sifive.com', library: 'MEM', name: 'SPRAM', version: '0.1.0'},
      abstractionTypes: [{
        viewRef: 'RTLview',
        portMaps: {
          CLK      : 'MEM_CLK2',
          WREN     : 'MEM_WREN',
          RDEN     : 'MEM_RDEN',
          BEN      : 'MEM_BEN',
          ADDR     : 'MEM_ADDR',
          WRDATA   : 'MEM_WRDATA',
          RDDATA   : 'MEM_RDDATA'
        }
      }],
    }],
  }
}
```

will emit a base module that looks like
```scala
  class LexampleBaseImp extends LazyRawModuleImp(this) {
    val blackbox = Module(new example(

    ))
    // interface wiring 2
    // busType: SPRAM, mode: master
    // port wiring
    ioBridgeSource.bundle.MEM_CLK1 := blackbox.io.MEM_CLK1
    ioBridgeSource.bundle.MEM_CLK2 := blackbox.io.MEM_CLK2
    ioBridgeSource.bundle.MEM_WREN := blackbox.io.MEM_WREN
    ioBridgeSource.bundle.MEM_RDEN := blackbox.io.MEM_RDEN
    ioBridgeSource.bundle.MEM_BEN := blackbox.io.MEM_BEN
    ioBridgeSource.bundle.MEM_ADDR := blackbox.io.MEM_ADDR
    ioBridgeSource.bundle.MEM_WRDATA := blackbox.io.MEM_WRDATA
    blackbox.io.MEM_RDDATA := ioBridgeSource.bundle.MEM_RDDATA
    // interface alias
    val MY_MEM0 = MY_MEMNode.out(0)._1
    // interface wiring
    // wiring for MY_MEM of type SPRAM
    // -> {"CLK":1,"WREN":1,"RDEN":1,"BEN":1,"ADDR":"addrWidth","WRDATA":"dataWidth","RDDATA":"-dataWidth"}
    MY_MEM0.CLK := blackbox.io.MEM_CLK2
    MY_MEM0.WREN := blackbox.io.MEM_WREN
    MY_MEM0.RDEN := blackbox.io.MEM_RDEN
    MY_MEM0.BEN := blackbox.io.MEM_BEN
    MY_MEM0.ADDR := blackbox.io.MEM_ADDR
    MY_MEM0.WRDATA := blackbox.io.MEM_WRDATA
    blackbox.io.MEM_RDDATA := MY_MEM0.RDDATA

  }
```
Those connections are what maps the memory interface signals to the actual blackbox signals. if I changed the port mapping of the `CLK` signal to `MEM_CLK1` then the emitted scala should look exactly the same except that the line `MY_MEM0.CLK := blackbox.io.MEM_CLK2` would be changed to `MY_MEM0.CLK := blackbox.io.MEM_CLK1`

**Comment by v-krvavac** [comment]
Thanks, I actually did that (changes are still local) but I figured out the issue is probably the fact that I don't have an output pin cpu clk on the PHY. I am assuming that Rambus expected the same cpu_clk that is provided to the PHY as an input will be provided to the memories, however, I only have that input cpu_clk and (as it could probably be expected) if I map that to CLK duh ignores it. 
The only thing I can think of at the moment (as a patch) is to use some random output signal to map to CLK in order to get Scala code, and then do manual changes to propagate the clock from the input to the memory interface instead of the "random" signal.

**Comment by albertchen-sifive** [comment]
ah I see. duh really should be throwing an error or warning when a portmap is missing rather than silently failing

**Comment by v-krvavac** [comment]
I am not sure what i am missing here, it seems like duh ignores some of the optional signals including CLK (RDERR is also ignored).
- In your example, I am not sure how the CLK mapping is successful since you declared the CLK as output of your example signal but in duh-bus i see that it is labeled as input on both master and slave:
ports: {
      CLK: {
        description: 'Memory clock',
        requiresDriver: true,
        isClock: true,
        wire: {
          onMaster: {width: 1, direction: 'in', presence: 'optional'},
          onSlave:  {width: 1, direction: 'in', presence: 'optional'}
        }
},

- I am using myproject.json5 file and I am running the following command from my local directory: duh-export-scala ../myproject.json5

Generated scala has something that looks like this (also note the unrelated issue of WR signal mapping being commented out in the generated code):
    // -> {"WREN":1,"RDEN":1,"BEN":1,"ADDR":"addrWidth","WRDATA":"dataWidth","RDDATA":"-dataWidth"}PMA0CPUDMEM0.WREN := blackbox.io.pma0_cpu_dmem_wr_strobe_o
    PMA0CPUDMEM0.RDEN := blackbox.io.pma0_cpu_dmem_rd_strobe_o
    PMA0CPUDMEM0.BEN := blackbox.io.pma0_cpu_dmem_byte_sel_o
    PMA0CPUDMEM0.ADDR := blackbox.io.pma0_cpu_dmem_addr_o
    PMA0CPUDMEM0.WRDATA := blackbox.io.pma0_cpu_dmem_wr_data_o
    blackbox.io.pma0_cpu_dmem_rd_data_i := PMA0CPUDMEM0.RDDATA

    // wiring for PMA1CPUDMEM of type SPRAM
    // -> {"WREN":1,"RDEN":1,"BEN":1,"ADDR":"addrWidth","WRDATA":"dataWidth","RDDATA":"-dataWidth"}PMA1CPUDMEM0.WREN := blackbox.io.pma1_cpu_dmem_wr_strobe_o
    PMA1CPUDMEM0.RDEN := blackbox.io.pma1_cpu_dmem_rd_strobe_o
    PMA1CPUDMEM0.BEN := blackbox.io.pma1_cpu_dmem_byte_sel_o
    PMA1CPUDMEM0.ADDR := blackbox.io.pma1_cpu_dmem_addr_o
    PMA1CPUDMEM0.WRDATA := blackbox.io.pma1_cpu_dmem_wr_data_o
    blackbox.io.pma1_cpu_dmem_rd_data_i := PMA1CPUDMEM0.RDDATA

**Comment by drom** [comment]
@v-krvavac please try `duh-scala@0.12.0`

**Comment by v-krvavac** [comment]
Hi, I can see the update, but I have a similar concert as I stated above. The CLK is defined as input on both master and slave interface. In this case, I have an input clock to the PHY that comes from the controller (no output cpu clock signal in the PHY), and if I map it to the memory bus interface CLK it outputs something like:
blackbox.io.pma1_cpu_clk_i := PMA1CPUDMEM0.CLK
which makes no sense since I want the opposite direction
So, currently I use manual hack which looks something like this:
    val pma0cpuclk = Wire(Bool())
    pma0cpuclk := blackbox.io.pma0_cpu_clk_i
    PMA0CPUDMEM0.CLK := pma0cpuclk
This way I can propagate the PHY input clock to the memory
