### ISSUE TITLE
Duh ignores parameters

### ISSUE THREAD

**Issue by v-krvavac** [sifive/duh-scala#5]
Duh only generates signal width parameters, it ignores the other parameters from the json file.
Example (pciebfm.json5) : 
    pSchema: {
      type: 'object',
      properties: {
         param_BFM_TYPE: {
            type: 'integer', minimum: 0, maximum: 1,
         },
.....
      oneOf: [{
         param_BFM_TYPE: {enum: [0]},
.....
     Those kind of parameters are ignored by duh, and do not appear in any way in generated scala

**Comment by drom** [comment]
That should be fixed in v0.4.0
