### ISSUE TITLE
wrong coupling of AXI master node to pbus

### ISSUE THREAD

**Issue by jordiflor** [sifive/duh-scala#9]
Scala compile error;
[error] /home/hdldh05/Sesame/plda_pcie_controller/ws1/plda-pcie-controller/scala/xpressrich4/src/xpressrich4-base.scala:963:62: value := is not a member of freechips.rocketchip.tilelink.TLOutwardNode
[error]   Expression does not convert to assignment because receiver is not assignable.
[error]     bap.pbus.coupleTo("axi") { xpressrich4_top.axi4_mst0Node := TLWidthWidget(bap.pbus) := _ }

AXI4 master node is a TLOutwardNode, it should be "coupledFrom", like:

 bap.cbus.coupleFrom("axi_mst0") { _ := TLWidthWidget(bap.cbus) := xpressrich4_top.axi4_mst0Node }

**Comment by drom** [comment]
That should be fixed in v0.4.0

**Comment by drom** [comment]
Please reopen if reappear.
